'use strict';
const $ = (id) => document.querySelector('#' + id);
const state = { education: [], experience: [], projects: [], certifications: [] };
function esc(v){return String(v ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function field(label,key,value,placeholder){return '<div class="builder-field"><label>'+label+'</label><input data-key="'+key+'" value="'+esc(value)+'" placeholder="'+esc(placeholder||'')+'"></div>';}
function area(label,key,value,placeholder){return '<div class="builder-field"><label>'+label+'</label><textarea data-key="'+key+'" placeholder="'+esc(placeholder||'')+'">'+esc(value)+'</textarea></div>';}
function renderEntries(type){const list=$(type+'List');const a=state[type];if(!a.length){list.innerHTML='<p class="builder-section-note">Nothing added yet.</p>';return;}list.innerHTML=a.map((x,i)=>{let body='';if(type==='education'){body='<div class="builder-two">'+field('SCHOOL','school',x.school,'University / College')+field('DEGREE / FIELD','degree',x.degree,'BS Computer Engineering')+'</div>'+field('YEAR','year',x.year,'2026');}else if(type==='experience'){body='<div class="builder-two">'+field('JOB TITLE','title',x.title,'Frontend Developer')+field('COMPANY','company',x.company,'Company name')+'</div>'+field('DURATION','duration',x.duration,'2024 — Present')+area('DESCRIPTION','description',x.description,'What you worked on and accomplished.');}else if(type==='projects'){body=field('PROJECT NAME','name',x.name,'JobPath')+area('DESCRIPTION','description',x.description,'What you built and the technologies you used.');}else{body='<div class="builder-two">'+field('CERTIFICATION','name',x.name,'AWS Certified ...')+field('ISSUER','issuer',x.issuer,'Issuing organization')+'</div>'+field('YEAR','year',x.year,'2026');}return '<div class="builder-entry" data-index="'+i+'">'+body+'<div class="builder-entry-actions"><button class="builder-remove" data-remove="'+i+'">Remove</button></div></div>';}).join('');list.querySelectorAll('.builder-entry').forEach((entry)=>{entry.querySelectorAll('[data-key]').forEach((el)=>el.addEventListener('input',()=>{state[type][Number(entry.dataset.index)][el.dataset.key]=el.value;renderPreview();}));entry.querySelector('[data-remove]').addEventListener('click',()=>{state[type].splice(Number(entry.dataset.index),1);renderEntries(type);renderPreview();});});}
function collect(){return {fullName:$('#fullName').value.trim(),email:$('#email').value.trim(),phone:$('#phone').value.trim(),location:$('#location').value.trim(),summary:$('#summary').value.trim(),education:state.education,experience:state.experience,projects:state.projects,certifications:state.certifications};}
function renderPreview(){const r=collect();const contact=[r.email,r.phone,r.location].filter(Boolean).join(' · ');let h='<h1>'+esc(r.fullName||'Your Name')+'</h1><div class="resume-contact">'+esc(contact||'email · phone · location')+'</div>';if(r.summary)h+='<h4>Profile</h4><p>'+esc(r.summary)+'</p>';if(r.experience.length)h+='<h4>Experience</h4>'+r.experience.map(x=>'<div class="resume-item"><strong>'+esc(x.title||'Job Title')+'</strong><div class="resume-muted">'+esc(x.company)+(x.duration?' · '+esc(x.duration):'')+'</div><p>'+esc(x.description)+'</p></div>').join('');if(r.projects.length)h+='<h4>Projects</h4>'+r.projects.map(x=>'<div class="resume-item"><strong>'+esc(x.name||'Project')+'</strong><p>'+esc(x.description)+'</p></div>').join('');if(r.education.length)h+='<h4>Education</h4>'+r.education.map(x=>'<div class="resume-item"><strong>'+esc(x.degree||'Degree')+'</strong><div class="resume-muted">'+esc(x.school)+(x.year?' · '+esc(x.year):'')+'</div></div>').join('');if(r.certifications.length)h+='<h4>Certifications</h4>'+r.certifications.map(x=>'<div class="resume-item"><strong>'+esc(x.name||'Certification')+'</strong><div class="resume-muted">'+esc(x.issuer)+(x.year?' · '+esc(x.year):'')+'</div></div>').join('');$('#resumePaper').innerHTML=h;}
function add(id,type,factory){$(id).addEventListener('click',()=>{state[type].push(factory());renderEntries(type);renderPreview();});}
async function load(){try{const a=await Promise.all([fetch('/api/resume/builder',{credentials:'include'}),fetch('/api/auth/profile',{credentials:'include'})]);if(a[1].status===401){location.href='/';return;}const p=(await a[1].json()).profile||{};const d=a[0].ok?(await a[0].json()).resume:null;const r=d||{fullName:p.full_name||'',email:p.email||'',phone:'',location:p.location||'',summary:'',education:[],experience:[],projects:[],certifications:[]};['fullName','email','phone','location','summary'].forEach(k=>{$(k).value=r[k]||'';$(k).addEventListener('input',renderPreview);});state.education=Array.isArray(r.education)?r.education:[];state.experience=Array.isArray(r.experience)?r.experience:[];state.projects=Array.isArray(r.projects)?r.projects:[];state.certifications=Array.isArray(r.certifications)?r.certifications:[];['education','experience','projects','certifications'].forEach(renderEntries);renderPreview();}catch(e){console.error('[builder] load error:',e);$('#builderStatus').textContent='Unable to load your resume.';}}
$('#saveResume').addEventListener('click',async()=>{const b=$('#saveResume'),s=$('#builderStatus');b.disabled=true;b.textContent='Saving...';try{const r=await fetch('/api/resume/builder',{method:'PUT',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({resume:collect()})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Failed to save resume.');s.textContent='Saved to your profile.';}catch(e){s.textContent=e.message;}finally{b.disabled=false;b.textContent='Save Resume';}});
$('#printResume').addEventListener('click',()=>window.print());
add('addEducation','education',()=>({school:'',degree:'',year:''}));
add('addExperience','experience',()=>({title:'',company:'',duration:'',description:''}));
add('addProject','projects',()=>({name:'',description:''}));
add('addCertification','certifications',()=>({name:'',issuer:'',year:''}));
load();