const SKILLS_LIST = [
    // Programming languages
    { name: 'Java', category: 'Programming Language' },
    { name: 'Python', category: 'Programming Language' },
    { name: 'C++', category: 'Programming Language' },
    { name: 'C#', category: 'Programming Language' },
    { name: 'C', category: 'Programming Language' },
    { name: 'JavaScript', category: 'Programming Language' },
    { name: 'TypeScript', category: 'Programming Language' },
    { name: 'PHP', category: 'Programming Language' },
    { name: 'Ruby', category: 'Programming Language' },
    { name: 'Go', category: 'Programming Language' },
    { name: 'Rust', category: 'Programming Language' },
    { name: 'Kotlin', category: 'Programming Language' },
    { name: 'Swift', category: 'Programming Language' },
    { name: 'Dart', category: 'Programming Language' },
    { name: 'R', category: 'Programming Language' },
    { name: 'MATLAB', category: 'Programming Language' },
    { name: 'SQL', category: 'Database' },
    { name: 'Visual Basic', category: 'Programming Language' },
    { name: 'VB.NET', category: 'Programming Language' },
    { name: '.NET', category: 'Framework' },

    // Web development
    { name: 'HTML', category: 'Web' },
    { name: 'HTML5', category: 'Web' },
    { name: 'XML', category: 'Web' },
    { name: 'CSS', category: 'Web' },
    { name: 'CSS3', category: 'Web' },
    { name: 'React', category: 'Web' },
    { name: 'React Native', category: 'Web' },
    { name: 'Angular', category: 'Web' },
    { name: 'Vue.js', category: 'Web' },
    { name: 'Node.js', category: 'Web' },
    { name: 'Express.js', category: 'Web' },
    { name: 'Next.js', category: 'Web' },
    { name: 'Nuxt.js', category: 'Web' },
    { name: 'Bootstrap', category: 'Web' },
    { name: 'Tailwind CSS', category: 'Web' },
    { name: 'jQuery', category: 'Web' },
    { name: 'REST API', category: 'Web' },
    { name: 'GraphQL', category: 'Web' },
    { name: 'Web Development', category: 'Web' },
    { name: 'Web Design', category: 'Web' },
    { name: 'Responsive Web Design', category: 'Web' },
    { name: 'Progressive Web Applications', category: 'Web' },

    // Backend / software engineering
    { name: 'Spring', category: 'Framework' },
    { name: 'Spring Boot', category: 'Framework' },
    { name: 'Django', category: 'Framework' },
    { name: 'Flask', category: 'Framework' },
    { name: 'Laravel', category: 'Framework' },
    { name: 'ASP.NET', category: 'Framework' },
    { name: 'Entity Framework', category: 'Framework' },
    { name: 'OOP', category: 'Concept' },
    { name: 'Object-Oriented Programming', category: 'Concept' },
    { name: 'Data Structures', category: 'Computer Science' },
    { name: 'Algorithms', category: 'Computer Science' },
    { name: 'Software Development', category: 'Software Engineering' },
    { name: 'Software Engineering', category: 'Software Engineering' },
    { name: 'Software Testing', category: 'Software Engineering' },
    { name: 'Unit Testing', category: 'Software Engineering' },
    { name: 'Test Automation', category: 'Software Engineering' },
    { name: 'Debugging', category: 'Software Engineering' },
    { name: 'API Development', category: 'Backend' },
    { name: 'Microservices', category: 'Backend' },
    { name: 'System Design', category: 'Software Engineering' },

    // Databases / data
    { name: 'MySQL', category: 'Database' },
    { name: 'PostgreSQL', category: 'Database' },
    { name: 'SQLite', category: 'Database' },
    { name: 'Oracle', category: 'Database' },
    { name: 'Microsoft SQL Server', category: 'Database' },
    { name: 'MongoDB', category: 'Database' },
    { name: 'Redis', category: 'Database' },
    { name: 'Database Management', category: 'Database' },
    { name: 'Database Administration', category: 'Database' },
    { name: 'Database Design', category: 'Database' },
    { name: 'Data Modeling', category: 'Data' },
    { name: 'Data Analysis', category: 'Analysis' },
    { name: 'Data Analytics', category: 'Analysis' },
    { name: 'Data Visualization', category: 'Analysis' },
    { name: 'Data Mining', category: 'Analysis' },
    { name: 'Business Intelligence', category: 'Analysis' },
    { name: 'Statistics', category: 'Analysis' },
    { name: 'Operations Analysis', category: 'Analysis' },
    { name: 'Microsoft Excel', category: 'Office' },
    { name: 'Excel', category: 'Office' },
    { name: 'Microsoft Access', category: 'Office' },
    { name: 'Power BI', category: 'Data Tool' },
    { name: 'Tableau', category: 'Data Tool' },
    { name: 'QlikView', category: 'Data Tool' },
    { name: 'Qlik Sense', category: 'Data Tool' },
    { name: 'SPSS', category: 'Data Tool' },
    { name: 'SAS', category: 'Data Tool' },

    // Cloud / DevOps / version control
    { name: 'Git', category: 'Tool' },
    { name: 'GitHub', category: 'Tool' },
    { name: 'GitLab', category: 'Tool' },
    { name: 'Bitbucket', category: 'Tool' },
    { name: 'Docker', category: 'DevOps' },
    { name: 'Kubernetes', category: 'DevOps' },
    { name: 'CI/CD', category: 'DevOps' },
    { name: 'Jenkins', category: 'DevOps' },
    { name: 'Linux', category: 'Operating System' },
    { name: 'Windows', category: 'Operating System' },
    { name: 'AWS', category: 'Cloud' },
    { name: 'Microsoft Azure', category: 'Cloud' },
    { name: 'Google Cloud Platform', category: 'Cloud' },
    { name: 'Cloud Computing', category: 'Cloud' },

    // Networking / cybersecurity
    { name: 'Computer Networking', category: 'Networking' },
    { name: 'TCP/IP', category: 'Networking' },
    { name: 'DNS', category: 'Networking' },
    { name: 'DHCP', category: 'Networking' },
    { name: 'Routing', category: 'Networking' },
    { name: 'Network Administration', category: 'Networking' },
    { name: 'Network Security', category: 'Security' },
    { name: 'Cybersecurity', category: 'Security' },
    { name: 'Information Security', category: 'Security' },
    { name: 'Web Security', category: 'Security' },
    { name: 'Application Security', category: 'Security' },
    { name: 'Penetration Testing', category: 'Security' },
    { name: 'Ethical Hacking', category: 'Security' },
    { name: 'Vulnerability Assessment', category: 'Security' },
    { name: 'Firewalls', category: 'Security' },

    // UI / UX / creative
    { name: 'UI/UX', category: 'Design' },
    { name: 'User Interface Design', category: 'Design' },
    { name: 'User Experience Design', category: 'Design' },
    { name: 'Information Architecture', category: 'Design' },
    { name: 'Wireframing', category: 'Design' },
    { name: 'Prototyping', category: 'Design' },
    { name: 'Figma', category: 'Design Tool' },
    { name: 'Adobe Photoshop', category: 'Design Tool' },
    { name: 'Photoshop', category: 'Design Tool' },
    { name: 'Adobe Illustrator', category: 'Design Tool' },
    { name: 'Illustrator', category: 'Design Tool' },
    { name: 'Adobe InDesign', category: 'Design Tool' },
    { name: 'Premiere Pro', category: 'Design Tool' },
    { name: 'After Effects', category: 'Design Tool' },
    { name: 'Dreamweaver', category: 'Design Tool' },
    { name: 'Graphic Design', category: 'Design' },
    { name: 'Typography', category: 'Design' },
    { name: 'Branding', category: 'Design' },
    { name: 'WordPress', category: 'CMS' },
    { name: 'Content Management System', category: 'CMS' },
    { name: 'SEO', category: 'Marketing' },
    { name: 'Search Engine Optimization', category: 'Marketing' },

    // Business / finance / accounting
    { name: 'Accounting', category: 'Accounting' },
    { name: 'Bookkeeping', category: 'Accounting' },
    { name: 'Financial Analysis', category: 'Finance' },
    { name: 'Financial Reporting', category: 'Finance' },
    { name: 'Financial Planning', category: 'Finance' },
    { name: 'Budgeting', category: 'Finance' },
    { name: 'Forecasting', category: 'Finance' },
    { name: 'Auditing', category: 'Accounting' },
    { name: 'Tax Preparation', category: 'Accounting' },
    { name: 'Accounts Payable', category: 'Accounting' },
    { name: 'Accounts Receivable', category: 'Accounting' },
    { name: 'Payroll', category: 'Accounting' },
    { name: 'QuickBooks', category: 'Accounting' },
    { name: 'QuickBooks Online', category: 'Accounting' },
    { name: 'Xero', category: 'Accounting' },
    { name: 'Oracle NetSuite', category: 'Business Software' },
    { name: 'Microsoft Outlook', category: 'Office' },
    { name: 'Microsoft Teams', category: 'Collaboration' },
    { name: 'Microsoft Office', category: 'Office' },
    { name: 'Google Workspace', category: 'Office' },
    { name: 'Google Docs', category: 'Office' },
    { name: 'Google Sheets', category: 'Office' },
    { name: 'Google Slides', category: 'Office' },
    { name: 'Business Administration', category: 'Business' },
    { name: 'Business Analysis', category: 'Business' },
    { name: 'Business Strategy', category: 'Business' },
    { name: 'Operations Management', category: 'Management' },
    { name: 'Operations Analysis', category: 'Analysis' },
    { name: 'Process Improvement', category: 'Management' },
    { name: 'Supply Chain Management', category: 'Business' },
    { name: 'Procurement', category: 'Business' },
    { name: 'Inventory Management', category: 'Business' },
    { name: 'Customer Relationship Management', category: 'Business' },
    { name: 'CRM', category: 'Business' },
    { name: 'HubSpot CRM', category: 'Business Software' },
    { name: 'Salesforce', category: 'Business Software' },
    { name: 'SAP', category: 'Business Software' },

    // Human resources
    { name: 'Human Resources', category: 'Human Resources' },
    { name: 'Recruitment', category: 'Human Resources' },
    { name: 'Talent Acquisition', category: 'Human Resources' },
    { name: 'Employee Relations', category: 'Human Resources' },
    { name: 'Performance Management', category: 'Human Resources' },
    { name: 'Training and Development', category: 'Human Resources' },
    { name: 'Onboarding', category: 'Human Resources' },
    { name: 'HR Administration', category: 'Human Resources' },
    { name: 'HRIS', category: 'Human Resources' },
    { name: 'Conflict Resolution', category: 'Human Resources' },

    // Healthcare
    { name: 'Patient Care', category: 'Healthcare' },
    { name: 'Patient Assessment', category: 'Healthcare' },
    { name: 'Clinical Documentation', category: 'Healthcare' },
    { name: 'Medical Terminology', category: 'Healthcare' },
    { name: 'Vital Signs', category: 'Healthcare' },
    { name: 'Medication Administration', category: 'Healthcare' },
    { name: 'First Aid', category: 'Healthcare' },
    { name: 'CPR', category: 'Healthcare' },
    { name: 'Basic Life Support', category: 'Healthcare' },
    { name: 'Phlebotomy', category: 'Healthcare' },
    { name: 'Laboratory Techniques', category: 'Healthcare' },
    { name: 'Medical Laboratory Science', category: 'Healthcare' },
    { name: 'Health Information Management', category: 'Healthcare' },
    { name: 'Healthcare Administration', category: 'Healthcare' },
    { name: 'Public Health', category: 'Healthcare' },
    { name: 'Nursing', category: 'Healthcare' },
    { name: 'Patient Education', category: 'Healthcare' },
    { name: 'Infection Control', category: 'Healthcare' },

    // Education
    { name: 'Teaching', category: 'Education' },
    { name: 'Lesson Planning', category: 'Education' },
    { name: 'Classroom Management', category: 'Education' },
    { name: 'Curriculum Development', category: 'Education' },
    { name: 'Instructional Design', category: 'Education' },
    { name: 'Assessment and Evaluation', category: 'Education' },
    { name: 'Educational Technology', category: 'Education' },
    { name: 'Training', category: 'Education' },
    { name: 'Tutoring', category: 'Education' },
    { name: 'Research Methods', category: 'Education' },

    // Engineering
    { name: 'AutoCAD', category: 'Engineering' },
    { name: 'SolidWorks', category: 'Engineering' },
    { name: 'CATIA', category: 'Engineering' },
    { name: 'Computer-Aided Design', category: 'Engineering' },
    { name: 'Engineering Design', category: 'Engineering' },
    { name: 'Mechanical Design', category: 'Engineering' },
    { name: 'Structural Analysis', category: 'Engineering' },
    { name: 'Civil Engineering', category: 'Engineering' },
    { name: 'Mechanical Engineering', category: 'Engineering' },
    { name: 'Electrical Engineering', category: 'Engineering' },
    { name: 'Electronics Engineering', category: 'Engineering' },
    { name: 'Industrial Engineering', category: 'Engineering' },
    { name: 'Chemical Engineering', category: 'Engineering' },
    { name: 'Quality Control', category: 'Engineering' },
    { name: 'Quality Assurance', category: 'Engineering' },
    { name: 'PLC Programming', category: 'Engineering' },
    { name: 'Embedded Systems', category: 'Engineering' },
    { name: 'Microcontrollers', category: 'Engineering' },
    { name: 'Circuit Analysis', category: 'Engineering' },
    { name: 'MATLAB Simulink', category: 'Engineering' },

    // Science / research
    { name: 'Scientific Research', category: 'Science' },
    { name: 'Laboratory Research', category: 'Science' },
    { name: 'Experimental Design', category: 'Science' },
    { name: 'Data Collection', category: 'Science' },
    { name: 'Research Methodology', category: 'Science' },
    { name: 'Technical Writing', category: 'Science' },
    { name: 'Scientific Writing', category: 'Science' },

    // Marketing / communications
    { name: 'Digital Marketing', category: 'Marketing' },
    { name: 'Social Media Marketing', category: 'Marketing' },
    { name: 'Content Marketing', category: 'Marketing' },
    { name: 'Market Research', category: 'Marketing' },
    { name: 'Email Marketing', category: 'Marketing' },
    { name: 'Copywriting', category: 'Communication' },
    { name: 'Content Writing', category: 'Communication' },
    { name: 'Technical Writing', category: 'Communication' },
    { name: 'Public Speaking', category: 'Communication' },
    { name: 'Presentation Skills', category: 'Communication' },
    { name: 'Communication', category: 'Professional' },
    { name: 'Customer Service', category: 'Professional' },
    { name: 'Client Relations', category: 'Professional' },

    // Hospitality / tourism
    { name: 'Hospitality Management', category: 'Hospitality' },
    { name: 'Hotel Management', category: 'Hospitality' },
    { name: 'Front Office Operations', category: 'Hospitality' },
    { name: 'Food and Beverage Management', category: 'Hospitality' },
    { name: 'Event Management', category: 'Hospitality' },
    { name: 'Event Planning', category: 'Hospitality' },
    { name: 'Tourism Management', category: 'Hospitality' },
    { name: 'Guest Relations', category: 'Hospitality' },
    { name: 'Housekeeping Management', category: 'Hospitality' },

    // Legal
    { name: 'Legal Research', category: 'Legal' },
    { name: 'Legal Writing', category: 'Legal' },
    { name: 'Legal Documentation', category: 'Legal' },
    { name: 'Case Management', category: 'Legal' },
    { name: 'Contract Management', category: 'Legal' },
    { name: 'Compliance', category: 'Legal' },

    // Skilled trades
    { name: 'Welding', category: 'Skilled Trade' },
    { name: 'Electrical Installation', category: 'Skilled Trade' },
    { name: 'Electrical Maintenance', category: 'Skilled Trade' },
    { name: 'Plumbing', category: 'Skilled Trade' },
    { name: 'Carpentry', category: 'Skilled Trade' },
    { name: 'Automotive Repair', category: 'Skilled Trade' },
    { name: 'Automotive Maintenance', category: 'Skilled Trade' },
    { name: 'Machine Operation', category: 'Skilled Trade' },
    { name: 'Preventive Maintenance', category: 'Skilled Trade' },

    // Project / professional skills
    { name: 'Project Management', category: 'Professional' },
    { name: 'Agile', category: 'Methodology' },
    { name: 'Scrum', category: 'Methodology' },
    { name: 'Kanban', category: 'Methodology' },
    { name: 'Critical Thinking', category: 'Professional' },
    { name: 'Problem Solving', category: 'Professional' },
    { name: 'Time Management', category: 'Professional' },
    { name: 'Leadership', category: 'Professional' },
    { name: 'Teamwork', category: 'Professional' },
    { name: 'Adaptability', category: 'Professional' },
    { name: 'Attention to Detail', category: 'Professional' },
    { name: 'Organization', category: 'Professional' },
    { name: 'Interpersonal Skills', category: 'Professional' },
    { name: 'Decision Making', category: 'Professional' },
    { name: 'Programming', category: 'Professional' },
];

module.exports = { SKILLS_LIST };
